package co.com.itau.services.security.validatepassword.v1.definitions;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by Apache CXF 2.6.6-redhat-3
 * 2020-02-20T16:44:56.577-05:00
 * Generated source version: 2.6.6-redhat-3
 * 
 */
@WebService(targetNamespace = "http://itau.com.co/services/security/validatepassword/v1/definitions", name = "validatePasswordPortType")
@XmlSeeAlso({co.com.itau.services.security.validatepassword.v1.schemas.ObjectFactory.class, com.itau.redhat.sso.commoncannonical.schemas.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ValidatePasswordPortType {

    @WebMethod(action = "doValidatePassword")
    @WebResult(name = "doValidatePasswordRs", targetNamespace = "http://itau.com.co/services/security/validatepassword/v1/schemas", partName = "Response")
    public co.com.itau.services.security.validatepassword.v1.schemas.DoValidatePasswordRsType doValidatePassword(
        @WebParam(partName = "Request", name = "doValidatePasswordRq", targetNamespace = "http://itau.com.co/services/security/validatepassword/v1/schemas")
        co.com.itau.services.security.validatepassword.v1.schemas.DoValidatePasswordRqType request
    );
}
