
package com.itau.redhat.sso.services.definitions;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import com.itau.redhat.sso.services.schemas.DoValidatePasswordRqType;
import com.itau.redhat.sso.services.schemas.DoValidatePasswordRsType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "validatePasswordPortType", targetNamespace = "http://itau.com.co/services/security/validatepassword/v1/definitions")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.itau.redhat.sso.commoncannonical.schemas.ObjectFactory.class,
    com.itau.redhat.sso.services.schemas.ObjectFactory.class
})
public interface ValidatePasswordPortType {


    /**
     * 
     * @param request
     * @return
     *     returns co.com.itau.services.security.validatepassword.v1.schemas.DoValidatePasswordRsType
     */
    @WebMethod(action = "doValidatePassword")
    @WebResult(name = "doValidatePasswordRs", targetNamespace = "http://itau.com.co/services/security/validatepassword/v1/schemas", partName = "Response")
    public DoValidatePasswordRsType doValidatePassword(
        @WebParam(name = "doValidatePasswordRq", targetNamespace = "http://itau.com.co/services/security/validatepassword/v1/schemas", partName = "Request")
        DoValidatePasswordRqType request);

}
