
package com.itau.redhat.sso.services.definitions;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import com.itau.redhat.sso.util.Constant;


/**
 * OSB Service
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "validatePasswordBindingQSService", targetNamespace = "http://itau.com.co/services/security/validatepassword/v1/definitions", wsdlLocation = Constant.URL_WEB_SERVICE)
public class ValidatePasswordBindingQSService
    extends Service
{

    private final static URL VALIDATEPASSWORDBINDINGQSSERVICE_WSDL_LOCATION;
    private final static WebServiceException VALIDATEPASSWORDBINDINGQSSERVICE_EXCEPTION;
    private final static QName VALIDATEPASSWORDBINDINGQSSERVICE_QNAME = new QName("http://itau.com.co/services/security/validatepassword/v1/definitions", "validatePasswordBindingQSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
        	String uri = System.getenv("DB_JDNI");
        	System.out.println("Uri de variable: " + uri);
            url = new URL(Constant.URL_WEB_SERVICE);
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VALIDATEPASSWORDBINDINGQSSERVICE_WSDL_LOCATION = url;
        VALIDATEPASSWORDBINDINGQSSERVICE_EXCEPTION = e;
    }

    public ValidatePasswordBindingQSService() {
        super(__getWsdlLocation(), VALIDATEPASSWORDBINDINGQSSERVICE_QNAME);
    }

    public ValidatePasswordBindingQSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), VALIDATEPASSWORDBINDINGQSSERVICE_QNAME, features);
    }

    public ValidatePasswordBindingQSService(URL wsdlLocation) {
        super(wsdlLocation, VALIDATEPASSWORDBINDINGQSSERVICE_QNAME);
    }

    public ValidatePasswordBindingQSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VALIDATEPASSWORDBINDINGQSSERVICE_QNAME, features);
    }

    public ValidatePasswordBindingQSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ValidatePasswordBindingQSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ValidatePasswordPortType
     */
    @WebEndpoint(name = "validatePasswordBindingQSPort")
    public ValidatePasswordPortType getValidatePasswordBindingQSPort() {
        return super.getPort(new QName("http://itau.com.co/services/security/validatepassword/v1/definitions", "validatePasswordBindingQSPort"), ValidatePasswordPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ValidatePasswordPortType
     */
    @WebEndpoint(name = "validatePasswordBindingQSPort")
    public ValidatePasswordPortType getValidatePasswordBindingQSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://itau.com.co/services/security/validatepassword/v1/definitions", "validatePasswordBindingQSPort"), ValidatePasswordPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VALIDATEPASSWORDBINDINGQSSERVICE_EXCEPTION!= null) {
            throw VALIDATEPASSWORDBINDINGQSSERVICE_EXCEPTION;
        }
        return VALIDATEPASSWORDBINDINGQSSERVICE_WSDL_LOCATION;
    }

}
